# Generated by Django 6.0.5 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    # O M2M `cabos` precisa ser reapontado para Lideranca ANTES de a 0018
    # apagar o modelo antigo CaboEleitoral — senão um banco zerado não migra
    # (o dev histórico passou porque aplicou na ordem de criação). Só ajusta o
    # grafo; nenhuma operação muda, bancos já migrados não são afetados.
    dependencies = [
        ('liderancas', '0017_migrar_dados_lideranca'),
        ('tarefas', '0009_promessa'),
    ]
    run_before = [
        ('liderancas', '0018_remove_interacaolog_apoiador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cabos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'papel': 'cabo'}, related_name='tarefas', to='liderancas.lideranca', verbose_name='Cabos Eleitorais'),
        ),
    ]
