# Generated by Django 6.0.5 on 2026-07-18 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0034_lideranca_formas_ajuda_and_more'),
        ('tarefas', '0014_itemchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='liderancas.lideranca', verbose_name='Contato (follow-up)'),
        ),
    ]
