# Generated by Django 6.0.5 on 2026-06-07 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0011_interacao_log'),
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='PIB (R$ mil)')),
                ('renda_per_capita', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Renda per capita')),
                ('familias_bolsa_familia', models.IntegerField(default=0, verbose_name='Famílias no Bolsa Família')),
                ('populacao', models.IntegerField(default=0)),
                ('meis_ativos', models.IntegerField(default=0, verbose_name='MEIs ativos')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de referência')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='liderancas.cidade')),
            ],
            options={
                'verbose_name': 'Indicador Municipal',
                'verbose_name_plural': 'Indicadores Municipais',
                'unique_together': {('cidade', 'ano_referencia')},
            },
        ),
    ]
