# Generated by Django 6.0.5 on 2026-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_indicador_municipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadormunicipal',
            name='anos_estudo_medio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Anos de estudo médio'),
        ),
        migrations.AddField(
            model_name='indicadormunicipal',
            name='idosos_60_mais',
            field=models.IntegerField(default=0, verbose_name='Idosos 60+'),
        ),
        migrations.AddField(
            model_name='indicadormunicipal',
            name='jovens_18_29',
            field=models.IntegerField(default=0, verbose_name='Jovens 18-29'),
        ),
        migrations.AddField(
            model_name='indicadormunicipal',
            name='populacao_rural',
            field=models.IntegerField(default=0, verbose_name='Pop. rural'),
        ),
        migrations.AddField(
            model_name='indicadormunicipal',
            name='populacao_urbana',
            field=models.IntegerField(default=0, verbose_name='Pop. urbana'),
        ),
    ]
