# Generated by Django 6.0.5 on 2026-06-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_votos', models.PositiveIntegerField(default=45000, verbose_name='Meta de votos')),
                ('meta_doacoes', models.PositiveIntegerField(default=120000, verbose_name='Meta de doações (R$)')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
