# Generated by Django 6.0.5 on 2026-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_add_imagem_evento'),
        ('liderancas', '0013_interacaolog_egresso_interacaolog_lassberg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='apoiadores',
            field=models.ManyToManyField(blank=True, related_name='compromissos', to='liderancas.apoiador', verbose_name='Apoiadores participantes'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='cabos',
            field=models.ManyToManyField(blank=True, related_name='compromissos', to='liderancas.caboeleitoral', verbose_name='Cabos participantes'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='coordenadores',
            field=models.ManyToManyField(blank=True, related_name='compromissos', to='liderancas.coordenadorregional', verbose_name='Coordenadores participantes'),
        ),
        migrations.AddField(
            model_name='compromisso',
            name='interacoes_geradas',
            field=models.BooleanField(default=False, help_text='Interações já criadas para os participantes ao realizar o compromisso.'),
        ),
    ]
