# Generated by Django 6.0.5 on 2026-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_migrar_secoes_liderancas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='areas_tarefas',
            field=models.JSONField(blank=True, default=list, help_text='Setores cujas tarefas o usuário enxerga (vazio = todas). Admin sempre vê todas.', verbose_name='Áreas de tarefas'),
        ),
    ]
