# Generated by Django 6.0.5 on 2026-07-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_areas_tarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='areas_tarefas',
            field=models.JSONField(blank=True, default=list, help_text='Setores cujas tarefas o usuário enxerga. Só as marcadas; nenhuma marcada = não vê nenhuma tarefa. Admin sempre vê todas.', verbose_name='Áreas de tarefas'),
        ),
    ]
