# Generated by Django 6.0.5 on 2026-06-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0014_apoiador_meta_votos_transferir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='adversario_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adversário (quem controla)'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='adversario_partido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Partido do adversário'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='controle',
            field=models.CharField(blank=True, choices=[('aliado', 'Aliado'), ('neutro', 'Neutro'), ('disputado', 'Em disputa'), ('adversario', 'Adversário')], help_text='Quem domina a cidade politicamente (vazio = não classificado).', max_length=12, verbose_name='Controle político'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='controle_manual',
            field=models.BooleanField(default=False, help_text='Marcado à mão — a auto-detecção não sobrescreve.'),
        ),
    ]
