# Generated by Django 6.0.5 on 2026-07-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0025_lideranca_atendente_lideranca_canal_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='tipos',
            field=models.JSONField(blank=True, default=list, help_text='Uma ou mais categorias; a primeira é a principal.', verbose_name='Categorias do Apoiador'),
        ),
    ]
