# Generated by Django 6.0.5 on 2026-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0030_alter_lideranca_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lideranca',
            name='niveis',
            field=models.JSONField(blank=True, default=list, help_text='Um ou mais níveis; o primeiro é o principal.', verbose_name='Níveis'),
        ),
        migrations.AlterField(
            model_name='lideranca',
            name='nivel',
            field=models.CharField(blank=True, choices=[('contato', 'Contato'), ('eleitor', 'Eleitor'), ('multiplicador', 'Multiplicador'), ('voluntario', 'Voluntário')], max_length=15, verbose_name='Nível'),
        ),
    ]
