# Generated by Django 6.0.5 on 2026-07-09 19:33

from django.db import migrations


def lead_para_contato(apps, schema_editor):
    """"Lead" foi renomeado para "Contato" no vocabulário de nível.
    Renomeia os registros existentes e faz o backfill de `niveis` a partir
    de `nivel` (para os cadastros anteriores ao campo múltiplo)."""
    Lideranca = apps.get_model('liderancas', 'Lideranca')
    Lideranca._base_manager.filter(nivel='lead').update(nivel='contato')
    for obj in Lideranca._base_manager.exclude(nivel='').iterator():
        atual = obj.niveis or []
        novo = ['contato' if n == 'lead' else n for n in atual]
        if not novo and obj.nivel:
            novo = [obj.nivel]
        if novo != atual:
            obj.niveis = novo
            obj.save(update_fields=['niveis'])


def contato_para_lead(apps, schema_editor):
    Lideranca = apps.get_model('liderancas', 'Lideranca')
    Lideranca._base_manager.filter(nivel='contato').update(nivel='lead')


class Migration(migrations.Migration):

    dependencies = [
        ('liderancas', '0031_lideranca_niveis_alter_lideranca_nivel'),
    ]

    operations = [
        migrations.RunPython(lead_para_contato, contato_para_lead),
    ]
